config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "guesses#index"
  get '/report', to: 'guesses#show', as: 'report'
  resources :guesses, only: [:create]
  get '/animal/:height/:weight', to: 'heights#animal', as: 'animal'
  get '/chart', to: 'animal_height_weights#index', as: 'chart'
end

app/models/animal_height_weight.rb
class AnimalHeightWeight < ApplicationRecord

  def dog_rows
    AnimalHeightWeight.where(animal: 'Dog').all()
  end

  def cat_rows
    AnimalHeightWeight.where(animal: 'Cat').all()
  end

  def data_set_label
    ['Height', 'Weight', 'Animal']
  end

  def training_set(limit = 200)
    AnimalHeightWeight.select([:height, :weight, :animal]).limit(limit).map{
      |e| [e.height.to_i, e.weight.to_i, e.animal.to_s]
    }
  end

  def testing_set(limit = 800, offset = 200)
    AnimalHeightWeight.select([:height, :weight, :animal]).limit(limit).offset(offset).map{
      |e| [e.height.to_i, e.weight.to_i, e.animal.to_s]
    }
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guess.rb
# == Schema Information
#
# Table name: guesses
#
#  id             :integer          not null, primary key
#  pet_guess      :string
#  height         :float
#  weight         :float
#  is_correct     :boolean          default(TRUE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
require 'decisiontree'

class Guess < ApplicationRecord

  validates :height, presence: true
  validates :weight, presence: true
  validates :pet_guess, presence: true

  def dog_wrong
    Guess.where('is_correct': false, pet_guess: 'Dog').all().count
  end

  def dog_right
    Guess.where('is_correct': true, pet_guess: 'Dog').all().count
  end

  def cat_wrong
    Guess.where('is_correct': false, pet_guess: 'Cat').all().count
  end

  def cat_right
    Guess.where('is_correct': true, pet_guess: 'Cat').all().count
  end

  def wrong_guesses
    Guess.where('is_correct': false).order("to_char(created_at,'DDDHH24MI')").group("to_char(created_at,'DDDHH24MI')").count
  end

  def correct_guesses
    Guess.where('is_correct': true).order("to_char(created_at,'DDDHH24MI')").group("to_char(created_at,'DDDHH24MI')").count
  end

  # random bias
  def bias
    ['Dog', 'Cat'].shuffle.first
  end

  # take all correct and incorect guesses to create an array of correct guesses
  def transfrom_training_set(results)
    data = results.each.map{|e|
      if e.is_correct === false and e.pet_guess === 'Dog'
        [e.height.to_i, e.weight.to_i, 'Cat']
      elsif e.is_correct === false and e.pet_guess === 'Cat'
        [e.height.to_i, e.weight.to_i, 'Dog']
      else
        [e.height.to_i, e.weight.to_i, e.pet_guess ]
      end
    }
    data
  end

  # get training data from guesess if none is found then it gets it from AnimalHeightWeight
  def training_set
    results = Guess.select([:is_correct, :height, :weight, :pet_guess]).limit(2000)

    data = transfrom_training_set(results)

    if data.count < 200
      self.training_set_seed()
    else
      data
    end
  end

  # get training data from AnimalHeightWeight model
  def training_set_seed(limit = 5000)
    ani_wh = AnimalHeightWeight.new
    ani_wh.training_set(limit)
  end

  # based on the trained model, guess the persons pet prefference
  def guess_animal(height, weight, animal = self.bias)
    ani_wh        = AnimalHeightWeight.new
    attributes    = ani_wh.data_set_label
    training      = self.training_set
    test          = [height, weight, animal]

    dec_tree = DecisionTree::ID3Tree.new(
      attributes, training, animal, Animal: :discrete, Height: :continuous, Weight: :continuous
    )
    dec_tree.train
    decision = dec_tree.predict(test)

    # puts "Predicted: #{decision} ... True decision: #{guess.last} ... Test #{guess}"

    decision
  end

end

app/controllers/animal_height_weights_controller.rb
class AnimalHeightWeightsController < ApplicationController
  def index
    @animals = AnimalHeightWeight.new
  end

  private
  def guess_params
    params.permit(:height, :weight, :animal_height_weight)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController

  def index
    @guess = Guess.new
  end

  def show
    @guess = Guess.new
  end

  def create
    @guess = Guess.new(guess_params)

    if @guess.save
      redirect_to "/"
    end
  end

  private
  def guess_params
    params.require(:guess).permit(:pet_guess, :height, :weight, :is_correct)
  end

end

app/controllers/heights_controller.rb
class HeightsController < ApplicationController
  def animal
    @guess = Guess.new(height_params)
    @result = @guess.guess_animal(@guess.height, @guess.weight, @guess.bias)
    render :layout => false
  end

  private
  def height_params
    params.permit(:height, :weight)
  end
end

app/helpers/animal_height_weights_helper.rb
module AnimalHeightWeightsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/heights_helper.rb
module HeightsHelper
end

app/views/animal_height_weights/index.html.erb
<h1>Linear Clasification</h1>

<div id="canvas-holder" style="width:150%;width:150%;left:-25%;position: relative;">
  <canvas id="scatter_dog"></canvas>
</div>

<%= javascript_tag do %>
var dog_data = document.getElementById('scatter_dog').getContext('2d');

var scatterChartDog = new Chart(dog_data, {
    type: 'scatter',
    data: {
        datasets: [{
            label: 'Dogs Dataset',
            borderColor: 'rgb(54, 162, 235)',
				    backgroundColor: 'rgb(54, 162, 235, 0.1)',
            data: [
              <% @animals.dog_rows.each do | dog| %>
                {x:<%= dog[:weight] %>, y: <%= dog[:height] %>},
              <% end %>
            ]
        },{
            label: 'Cats Dataset',
            borderColor: 'rgb(255, 99, 132)',
				    backgroundColor: 'rgb(255, 99, 132, 0.1)',
            data: [
              <% @animals.cat_rows.each do |cat| %>
                {x: <%= cat[:weight] %>, y: <%= cat[:height] %>},
              <% end %>
            ]
        }]
    },
    options: {
        animation: {
            duration: 0 // general animation time
        },
        scales: {
            xAxes: [{
                type: 'linear',
                position: 'bottom'
            }]
        }
    }
});


<% end %>

app/views/guesses/_results.html.erb
<div id="results" class="container invisible">
  <div class="row">
    <div class="col">
       <div id="dog_lover" class="d-none p-5">
         <h2>You are a Dog Lover?</h2>
         <img src="http://www.placepuppy.net/200/200" class="img-thumbnail" alt="Puppy">
       </div>
       <div id="cat_lover" class="d-none p-5">
         <h2>You are a Cat Lover?</h2>
         <img src="//placekitten.com/200/200" class="img-thumbnail" alt="Kitten">
       </div>
       <%= f.hidden_field(:pet_guess, {value: 'Dog'}) %>
    </div>
  </div>
  <div class="row ">
    <div class="col text-right">
      <%= f.button :Wrong, class:"btn btn-danger btn-lg" %>
    </div>
    <div class="col text-left">
       <%= f.button :Correct, class:"btn btn-success btn-lg", name: "guess[is_correct]", value:"1"  %>
    </div>
  </div>
</div>

app/views/guesses/index.html.erb
<main role="main" class="inner cover">

  <h1 class="cover-heading">Are you a Dog or Cat Person? </h1>
  <p class="lead">Let us guess whether or not you are a dog or cat person.
    <br />Enter your height and weight to see if you are a Dog or Cat person.
  </p>

  <div>
    <%= form_for(Guess.new, :url => { :action => "create" }) do |f| %>
      <div class="container">
        <div class="row">
          <div class="col">
            <%= f.select(:height, [], {},{ :class => 'custom-select custom-select-lg' }) do %>
              <% height = (54..80).to_a.map { |inch| [ (inch/12).floor.to_s+'\''+(inch%12).to_s, inch.to_s ] } %>
              <%= options_for_select(height) %>
            <% end %>
          </div>
          <div class="col">
            <%= f.number_field :weight, placeholder: 'Weight, lbs', class: "form-control form-control-lg", maxlength: "3", minlength: "2", 'data-toggle'=>"tooltip", 'data-placement'=>"bottom", 'title'=>"Enter your body weight in lbs, a number above 63" %>
          </div>
          <div class="col">
            <a type="button" name="button" id="guess" class="btn btn-primary btn-lg btn-block">Guess</a>
          </div>
        </div>
      </div>
      <%= render 'results', {f: f} %>
    <% end %>
  </div>

</main>

<div id="chart-container" class="container-fluid">
  <div class="row">
    <div id="canvas-holder" style="width:100%">
      <canvas id="chart"></canvas>
    </div>
    <%= javascript_tag do %>
      document.addEventListener('DOMContentLoaded', function(){
        renderChart(<%= @guess.cat_right %>, <%= @guess.cat_wrong %>, <%= @guess.dog_right %>, <%= @guess.dog_wrong %>);
      });
    <% end %>
  </div>
</div>

app/views/guesses/show.html.erb
<h1>Wrong Guess Report</h1>
<div id="canvas-holder" style="width:150%;width:150%;left:-25%;position: relative;">
  <canvas id="correct_guesses"></canvas>

</div>

<%= javascript_tag do %>
var correct_guesses = document.getElementById('correct_guesses').getContext('2d');


var scatterGorrectguesses = new Chart(correct_guesses, {
    type: 'bubble',
    data: {
        datasets: [{
            label: 'Wrong Guesses',
            borderColor: 'rgb(54, 162, 235)',
				    backgroundColor: 'rgb(54, 162, 235, 0.1)',
            radius: 20,
            borderWidth: 3,
            data: [
            <% @guess.wrong_guesses.each do | key, value| %>
              {x:<%= key %>, y: <%= value %>, r:(<%= value %> * 5)},
            <% end %>
            ]
        }]
    },
    options: {
        animation: {
            duration: 0 // general animation time
        },
        scales: {
            xAxes: [{
                type: 'linear',
                position: 'bottom'
            }]
        }
    }
});


<% end %>

app/views/heights/animal.html.erb
{"guess":"<%= @result %>"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Are you a Dog or Cat Person</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">The Guessing Machine</h3>
          <nav class="nav nav-masthead justify-content-center">
            <%= link_to 'Home', root_path, class:'nav-link' %>
            <%= link_to 'Raw Data', chart_path, class:'nav-link' %>
            <%= link_to 'Accuracy Report', report_path, class:'nav-link' %>
          </nav>
        </div>
      </header>

      <%= yield %>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p><small>© 2019 The GuessMaching, Inc. Terms Privacy Security </small></p>
        </div>
      </footer>

    </div>

    <%= javascript_include_tag 'main' %>

  </body>
</html>